// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: house.proto

package house

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type House struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Unit    uint32 `protobuf:"varint,3,opt,name=unit,proto3" json:"unit,omitempty"`
	// Types that are assignable to Dimension:
	//
	//	*House_Long
	//	*House_Wide
	Dimension isHouse_Dimension `protobuf_oneof:"dimension"`
}

func (x *House) Reset() {
	*x = House{}
	if protoimpl.UnsafeEnabled {
		mi := &file_house_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *House) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*House) ProtoMessage() {}

func (x *House) ProtoReflect() protoreflect.Message {
	mi := &file_house_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use House.ProtoReflect.Descriptor instead.
func (*House) Descriptor() ([]byte, []int) {
	return file_house_proto_rawDescGZIP(), []int{0}
}

func (x *House) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *House) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *House) GetUnit() uint32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (m *House) GetDimension() isHouse_Dimension {
	if m != nil {
		return m.Dimension
	}
	return nil
}

func (x *House) GetLong() float64 {
	if x, ok := x.GetDimension().(*House_Long); ok {
		return x.Long
	}
	return 0
}

func (x *House) GetWide() float64 {
	if x, ok := x.GetDimension().(*House_Wide); ok {
		return x.Wide
	}
	return 0
}

type isHouse_Dimension interface {
	isHouse_Dimension()
}

type House_Long struct {
	Long float64 `protobuf:"fixed64,4,opt,name=long,proto3,oneof"`
}

type House_Wide struct {
	Wide float64 `protobuf:"fixed64,5,opt,name=wide,proto3,oneof"`
}

func (*House_Long) isHouse_Dimension() {}

func (*House_Wide) isHouse_Dimension() {}

var File_house_proto protoreflect.FileDescriptor

var file_house_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x7e, 0x0a, 0x05, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74,
	0x12, 0x14, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00,
	0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x04, 0x77, 0x69, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x04, 0x77, 0x69, 0x64, 0x65, 0x42, 0x0b, 0x0a, 0x09,
	0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x62, 0x2f,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_house_proto_rawDescOnce sync.Once
	file_house_proto_rawDescData = file_house_proto_rawDesc
)

func file_house_proto_rawDescGZIP() []byte {
	file_house_proto_rawDescOnce.Do(func() {
		file_house_proto_rawDescData = protoimpl.X.CompressGZIP(file_house_proto_rawDescData)
	})
	return file_house_proto_rawDescData
}

var file_house_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_house_proto_goTypes = []interface{}{
	(*House)(nil), // 0: goprotobuf.House
}
var file_house_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_house_proto_init() }
func file_house_proto_init() {
	if File_house_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_house_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*House); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_house_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*House_Long)(nil),
		(*House_Wide)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_house_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_house_proto_goTypes,
		DependencyIndexes: file_house_proto_depIdxs,
		MessageInfos:      file_house_proto_msgTypes,
	}.Build()
	File_house_proto = out.File
	file_house_proto_rawDesc = nil
	file_house_proto_goTypes = nil
	file_house_proto_depIdxs = nil
}
